print(R.version.string)
source("corr.R")
source("complete.R")
cr <- corr("/media/soundarzozm/New Volume/Data Science/Datasets/rprog_data_specdata/specdata", 150)
head(cr)
summary(cr)
cr <- corr("/media/soundarzozm/New Volume/Data Science/Datasets/rprog_data_specdata/specdata", 400)
head(cr)
summary(cr)
cr <- corr("/media/soundarzozm/New Volume/Data Science/Datasets/rprog_data_specdata/specdata", 5000)
summary(cr)
length(cr)
cr <- corr("/media/soundarzozm/New Volume/Data Science/Datasets/rprog_data_specdata/specdata")
summary(cr)
length(cr)